#!/usr/bin/env bash

value=$(brightnessctl g --percentage)
progress=$(awk "BEGIN { printf \"%.2f\", $value / 100 }")
swayosd-client --custom-icon="display-brightness-symbolic" --custom-progress="$progress"