source = ./colors.conf

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0
    
    border_part_of_window = false

    shadow {
        enabled = true
        range = 14
        render_power = 3
        color = $base
    }

    blur {
        enabled = false
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

animations {
    enabled = true

    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    bezier = easeout,        0.25, 0.1,  0.25, 1

    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     10,    default     
    animation = border,        1,     3.39,  easeOutQuint
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = windows,       1,     4.79,  almostLinear
    animation = windowsIn,     1,     0.7,   almostLinear, popin 87%
    animation = windowsOut,    1,     1.3,   almostLinear, popin 87%
    animation = windowsMove,   1,     1.5,   almostLinear
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = fade,          1,     1.03,  quick       
    animation = fadeIn,        1,     1.1,   almostLinear
    animation = fadeOut,       1,     1.1,   almostLinear
    animation = fadeDpms,      1,     10,    easeout
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = workspaces,    1,     1.5,   almostLinear, fade
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = layers,        1,     1,     almostLinear, fade
    animation = layersIn,      1,     1,     almostLinear, fade
    animation = layersOut,     1,     1.1,   almostLinear, fade
}
