decoration {
    rounding = 16
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0
    
    border_part_of_window = false

    shadow {
        enabled = true
        range = 4
        render_power = 4
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = false
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

animations {
    enabled = true
    workspace_wraparound = false

    # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    bezier = easeOutExpo, 0.16, 1, 0.3, 1

    bezier = easeoutquad, 0.25, 0.46, 0.45, 0.94
    bezier = easeout, 0.25, 0.1, 0.25, 1

    #ONOFF use 0 to disable, 1 to enable. Note: if it's 0, you can omit further args.
    #SPEED is the amount of ds (1ds = 100ms) the animation will take.
    #CURVE is the bezier curve name, see curves.
    #STYLE (optional) is the animation style.

    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     10,    default     
    animation = border,        1,     3.39,  easeOutQuint
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = windows,       1,     4.79,  almostLinear
    animation = windowsIn,     1,     0.7,   almostLinear, popin 87%
    animation = windowsOut,    1,     1.3,   almostLinear, popin 87%
    animation = windowsMove,   1,     1.5,   almostLinear
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = fade,          1,     1.03,  quick       
    animation = fadeIn,        1,     1.1,   almostLinear
    animation = fadeOut,       1,     1.1,   almostLinear
    animation = fadeDpms,      1,     10,     easeout
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = workspaces,    1,     1.5,   almostLinear, slidevert
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = layers,        1,     1,     almostLinear, fade
    animation = layersIn,      1,     1,     almostLinear, fade
    animation = layersOut,     1,     1.1,   almostLinear, fade
}