source = ./colors.conf

general {
    gaps_in = 6
    gaps_out = 16

    border_size = 3
    col.active_border = $iris
    col.inactive_border = $overlay

    resize_on_border = true
    extend_border_grab_area = 15

    allow_tearing = false

    layout = dwindle
    
    snap {
       enabled = true
       respect_gaps = true
    }
}

dwindle {
    pseudotile = true
    preserve_split = true
}

debug {
    damage_tracking = 1 # weird bug with waybar tray menu where it flickers on dismiss having this on 2
}