source = ./colors.conf

general {
    gaps_in = 6
    gaps_out = 16

    border_size = 3
    col.active_border = $iris
    col.inactive_border = $overlay

    resize_on_border = true
    extend_border_grab_area = 15

    allow_tearing = false

    layout = dwindle
    
    snap {
       enabled = true
       respect_gaps = true
    }
}

dwindle {
    pseudotile = true
    preserve_split = true
}

group {
    drag_into_group = 2

    col.border_active = $foam
    col.border_inactive = $muted
    col.border_locked_active = $pine
    col.border_locked_inactive = $overlay

    groupbar {
        font_size = 12
        font_weight_active = bold
        font_weight_inactive = bold
        gradients = true
        height = 22
        indicator_gap = 0
        indicator_height = 0
        stacked = false
        priority = 3
        render_titles = true
        text_offset = 0
        text_padding = 5
        scrolling = true
        gradient_rounding = 11
        gradient_rounding_power = 2.0
        round_only_edges = true
        gradient_round_only_edges = false

        # Colors
        col.active = $foam
        col.inactive = $muted
        col.locked_active = $pine
        col.locked_inactive = $overlay

        # Text colors
        text_color = $overlay
        text_color_inactive = $overlay
        text_color_locked_active = $text
        text_color_locked_inactive = $text

        gaps_in = 6
        gaps_out = 6
        keep_upper_gap = false
        blur = false
    }
}

debug {
    damage_tracking = 1 # weird bug with waybar tray menu where it flickers on dismiss having this on 2
}