general {
    gaps_in = 6
    gaps_out = 12

    border_size = 3
    col.active_border = rgba(C061CBff)
    col.inactive_border = rgba(210a24ff)

    resize_on_border = true
    extend_border_grab_area = 15

    allow_tearing = false

    layout = dwindle
    
    snap {
       enabled = true
       respect_gaps = true
    }
}

dwindle {
    pseudotile = true
    preserve_split = true
}
