windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = onlyoffice-dialog-center
    match:class = DesktopEditors
    match:float = true

    center = true
}

# windowrule {
#     name = fix-flameshot
#     match:class = flameshot
    
#     no_anim = true
#     float = true
#     move = 0 0
# }

windowrule {
    name = nmtui
    match:class = nmtui
    
    float = true
    center = true
    size = 1000 700
    pin = true
    dim_around = true
}

windowrule {
    name = blueman
    match:class = blueman-manager

    float = true
    center = true
    size = 1000 700
    pin = true
    dim_around = true
}

# windowrule { # Bottom popup
#     name = fix-ugeeTablet1
#     match:class = ugeeTablet
#     match:title = ugeeTablet
#     match:xwayland = true
    
#     no_anim = true
#     float = true
#     pin = true
#     no_focus = true
#     rounding = 2
#     border_size = 0
# }

# windowrule { # Driver settings window
#     name = fix-ugeeTablet2
#     match:class = ugeeTablet
#     match:title = Pentablet
#     match:xwayland = true
    
# }

layerrule {
  name = no-anim-selection
  match:namespace = selection

  no_anim = true
}

layerrule {
    name = rofi-slide
    match:namespace = rofi

    #animation = slide
    dim_around = true
}

windowrule = match:class (pinentry-)(.*), stay_focused true
