windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120

    float = true
}

windowrule {
    name = onlyoffice-dialog-center
    match:class = DesktopEditors
    match:float = true

    center = true
}

layerrule {
  name = no_anim_selection
  no_anim = true
  match:namespace = selection
}

windowrule = no_anim true, match:class flameshot
windowrule = float true, match:class flameshot
windowrule = move 0 0, match:class flameshot
#windowrule = pin true, match:class flameshot
windowrule = monitor 0, match:class flameshot

windowrule = match:class (pinentry-)(.*), stay_focused true
