exec-once = waybar
exec-once = hyprpaper
exec-once = swaync
exec-once = flameshot
#exec-once = elephant
#exec-once = walker --gapplication-service

exec-once = systemctl --user start hyprpolkitagent
exec-once = cursor-clip --daemon
exec-once = swayosd-server
exec-once = hypridle
exec-once = blueman-applet
exec-once = nm-applet

# disable the horribly positioned power button
exec-once = systemd-inhibit --who="Hyprland config" --why="wlogout keybind" --what=handle-power-key --mode=block sleep infinity & echo $! > /tmp/.hyprland-systemd-inhibit
exec-shutdown = kill -9 "$(cat /tmp/.hyprland-systemd-inhibit)"
bindr = , XF86PowerOff, exec,
