exec-once = hyprctl setcursor macOS-hypr 28
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" # GTK4
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark" # GTK3

exec-once = uwsm app -- ~/.config/dotfiles-scripts/rofi-polkit
exec-once = uwsm app -- cursor-clip --daemon
exec-once = uwsm app -- udiskie -s
exec-once = uwsm app -- wlsunset -l 25 -L 67
exec = hyprpm reload

# disable the horribly positioned power button
exec-once = systemd-inhibit --who="Hyprland config" --why="awful location" --what=handle-power-key --mode=block sleep infinity & echo $! > /tmp/.hyprland-systemd-inhibit
exec-shutdown = kill -9 "$(cat /tmp/.hyprland-systemd-inhibit)"
bindr = , XF86PowerOff, exec,
