background = 0xff191724
base = 0xff1f1d2e
text = 0xffe0def4
alternate_base = 0xff26233a
bright_text = 0xffe0def4
accent = 0xffc4a7e7
accent_secondary = 0xff9ccfd8
h1_size = 24
h2_size = 18
h3_size = 15
font_size = 12
small_font_size = 10
icon_theme = Papirus-Dark
font_family = Adwaita Sans
font_family_monospace = Adwaita Sans Mono
rounding_large = 8
rounding_small = 5