misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true

    enable_anr_dialog = false
   
    middle_click_paste = false
    
    background_color = 0xff191724
    font_family = Adwaita Sans
}

debug {
    damage_tracking = 1 # weird bug with waybar tray menu where it flickers on dismiss having this on 2
}